### ISSUE TITLE
Pool fork 2 died, spawning replacement worker.

### ISSUE THREAD

**Issue by voipcall** [swap-dev/cryptonote-swap-pool#5]
node init.js -config=swap.json
2021-02-19 01:23:14 [master] Starting Cryptonote Node.JS pool version v1.3.5
2021-02-19 01:23:14 [master] Pool spawned on 2 thread(s)
/home/user/pool/node_modules/mailgun.js/dist/mailgun.js:2
!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.mailgun=t():e.mailgun=t()}(this,(function(){return(()=>{var e={271:(e,t,r)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0});var n=r(185);class o extends n.EventTarget{constructor(){throw super(),new TypeError("AbortSignal cannot be constructed directly")}get aborted(){const e=i.get(this);if("boolean"!=typeof e)throw new TypeError("Expected 'this' to be an 'AbortSignal' object, but got "+(null===this?"null":typeof this));return e}}n.defineEventAttribute(o.prototype,"abort");const i=new WeakMap;Object.defineProperties(o.prototype,{aborted:{enumerable:!0}}),"function"==typeof Symbol&&"symbol"==typeof Symbol.toStringTag&&Object.defineProperty(o.prototype,Symbol.toStringTag,{configurable:!0,value:"AbortSignal"});class s{constructor(){a.set(this,function(){const e=Object.creat

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/pool/lib/email.js:13:15)
2021-02-19 01:23:16 [chartsDataCollector] Started
2021-02-19 01:23:16 [master] Block unlocker died, spawning replacement...

**Comment by SoraKohaku** [comment]
same here lol. how to fixed this. npm already updates

**Comment by LPHuynh** [comment]
I can't replicate this issue. What version of node.js are you guys using?
Make sure that npm install succeeded without errors or try using node 12.

**Comment by SoraKohaku** [comment]
![Screenshot_20210327-172247](https://user-images.githubusercontent.com/11433397/112717919-3bceca00-8f22-11eb-936a-89b98aca46fa.png)
That same why like that?sigh need reinstall new server node 15. Will try 12

**Comment by LPHuynh** [comment]
odd number node.js version are unstable and it looks like you're not running the pool from the correct folder.
